# Generated by Django 4.1.7 on 2024-01-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
