# Generated by Django 4.1.7 on 2024-01-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemperatureData',
            new_name='WeatherState',
        ),
    ]
